DROP DATABASE IF EXISTS userappdb;
DROP USER IF EXISTS `userappadmin`@`%`;
CREATE DATABASE IF NOT EXISTS userappdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `userappadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `userappdb`.* TO `userappadmin`@`%`;